### ISSUE TITLE
Support release version numbers for start/end range

### ISSUE THREAD

**Issue by ehuss** [rust-lang/cargo-bisect-rustc#146]
## Problem

Often I know a regression happened between two specific stable versions of Rust.  However, it is not terribly easy to use cargo-bisect-rustc with a range of those two releases.  

## Proposed Solution

Support release tags in `--start` and `--end` (in addition to dates and hashes).

I think the commit can be found with `git merge-base master $TAG`, though I'm not certain that will always work.

**Comment by Kobzol** [comment]
I tried to add support for resolving tags and it can be done quite easily by using `revparse_ext` instead of `revparse_single` for parsing revisions for the local resolves (the GitHub backend can resolve tags directly). Then I realized that resolving tags is not the problem at all :D The problem is that release commits are not in `master`. I sent a PR: https://github.com/rust-lang/cargo-bisect-rustc/pull/147

**Comment by Kobzol** [comment]
Should be resolved by https://github.com/rust-lang/cargo-bisect-rustc/pull/147.

**Comment by ehuss** [comment]
Yep, thanks!
