### ISSUE TITLE
If rustup does not exist, error is very opaque

### ISSUE THREAD

**Issue by nagisa** [rust-lang/cargo-bisect-rustc#31]
Outputs a simple "No such file or directory (os error 2)".

**Comment by ehuss** [comment]
I'm going to close since I think this is partially resolved. I'm not sure exactly what part of the output this was coming from. If the issue is that you don't have rustup at all, then with `-vv`, you should get an output like:

```
error: no such command: `+bisector-ci-5f40394baa07b6fb50bc70dedd8b780524b20934-aarch64-apple-darwin`

	Cargo does not handle `+toolchain` directives.
	Did you mean to invoke `cargo` through `rustup` instead?
```

which I think should provide a clue that it needs rustup. (#205 is tracking being better about showing output.)

If the issue is that the `rustup` binary is missing, then you get the error:

```
ERROR: Could not run subcommand "rustup" "toolchain" "link" "bisector-nightly-2024-02-13-aarch64-apple-darwin" "/Users/eric/.rustup/toolchains/nightly-aarch64-apple-darwin": No such file or directory (os error 2)

Caused by:
    No such file or directory (os error 2)
```
