### ISSUE TITLE
find MSRV

### ISSUE THREAD

**Issue by danieleades** [rust-lang/cargo-bisect-rustc#76]
i'd like to use this tool to find the minimum supported rust version for my crate. Is that a supported use-case?

This will take a long time to run, as i don't know at what point features i'm relying on were added to the compiler.

cargo bisect seems to default to 2 days at a time, which is fine if you know the regression was fairly recent.

Is this configurable? is there some configuration i can use to make the bisection time delta grow (exponentially) with every iteration?

**Comment by danieleades** [comment]
update: i'm quite a few iterations in now, and it looks like the delta *is* slowly growing.

**Comment by chrissimpkins** [comment]
I think that this may be the block that you want:

https://github.com/rust-lang/cargo-bisect-rustc/blob/a5f50340105f2983bccef97a933f9d21a1d1d278/src/main.rs#L733-L745

**Comment by danieleades** [comment]
@chrissimpkins cheers! that clears that up.

even at 14 days it's going to be a slow process to go back potentially several years

**Comment by chrissimpkins** [comment]
Good luck!

**Comment by shepmaster** [comment]
This is something that I'm generally interested in, so I'll chime in with some thoughts.

When I've done this, I've done the *much* simpler quickly-hacked script (this version is from memory and may not be exactly right:

```bash
for minor in $(seq 42 1); do 
  version="1.${minor}.0"
  rustup install "${version}"
  cargo "+${version}" test
end
```

I then scan the list for the first failure.

However, that version is only partially useful. The problem is that it completely ignores dependencies. They come into play in a few ways:

1. **Many** crates incorrectly state their minimum dependency version. For example, they say `thing = "1.0"` when they *actually* need 1.4, or they say `thing = "1.4"` when they would have compiled with 1.0. 
1. Many crates don't document their MSRV or how they change their version number to indicate a MSRV change.
1. If a dependency does have their own MSRV, then your MSRV probably has to be equal to or newer than that version. Since the MSRV isn't (yet) accessible in a machine-readable format, this means you have to figure this out manually for each dependency (including transitive ones)

In practice, I've taken to finding "milestone releases" and targeting those. For example, Rust 1.15 (proc macros), 1.24 (impl trait), 1.31 (edition 2018), etc.

I then set up CI jobs to ensure that [my minimum dependency versions are correct](https://github.com/shepmaster/snafu/blob/7877691b7a159428a15729e0999af59e31ba1944/.cirrus.yml#L118-L123) and that I can compile on [my MSRV](https://github.com/shepmaster/snafu/blob/7877691b7a159428a15729e0999af59e31ba1944/.cirrus.yml#L145-L158).

**Comment by danieleades** [comment]
@shepmaster thanks for the input.

I'm all for formalising the MSRV as part of a crate's metadata, but then of course as you've pointed out you have to hope that author's aren't abusing it.

The process you've described above is about where I'm at- i've found a milestone release that my project builds against, and then set up CI to ensure that version continues to build my project. If i ever decide i want some shiny new feature (or one of my dependencies does!) i'll make a decision about bumping the MSRV and release at that point.

For a brand new crate finding the minimum (stable) compiler version the first time round wasn't too hard, but it was a bit mandraulic. Would be really nice if a tool like cargo-bisect-rustc could support finding the minimum compiler version, and it doesn't strike me as too wildly far outside what its doing already. Allowing the step size to continue growing in some adaptive fashion would be a big help, for example. An option to target stable compiler versions could be another.

**Comment by LingMan** [comment]
There's [cargo-msrv](https://github.com/foresterre/cargo-msrv), which - as far as I can tell - covers this specific use case.

**Comment by danieleades** [comment]
> There's [cargo-msrv](https://github.com/foresterre/cargo-msrv), which - as far as I can tell - covers this specific use case.

It sure does! I've been making use of it for the last two years since I posted that comment
